#!/usr/bin/env bash
# Kiro Gateway - One-line installer for Linux and macOS
# Usage: curl -fsSL https://raw.githubusercontent.com/redok07/kiro-gateway/main/install.sh | bash
#
# What this does:
#   1. Checks Python 3.10+ is available
#   2. Creates ~/.kiro-gateway/ with a virtual environment
#   3. Installs kiro-gateway from GitHub via pip
#   4. Creates a shell wrapper in ~/.kiro-gateway/bin/
#   5. Adds ~/.kiro-gateway/bin to your PATH (shell profile)
#   6. Creates a starter .env if none exists
#
# Re-running this script upgrades an existing installation safely.

set -euo pipefail

REPO="https://github.com/redok07/kiro-gateway.git"
INSTALL_DIR="$HOME/.kiro-gateway"
BIN_DIR="$INSTALL_DIR/bin"
VENV_DIR="$INSTALL_DIR/venv"
ENV_FILE="$INSTALL_DIR/.env"
MIN_PYTHON="3.10"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

info()  { printf "${CYAN}[info]${RESET}  %s\n" "$1"; }
ok()    { printf "${GREEN}[ok]${RESET}    %s\n" "$1"; }
warn()  { printf "${YELLOW}[warn]${RESET}  %s\n" "$1"; }
fail()  { printf "${RED}[error]${RESET} %s\n" "$1"; exit 1; }

# --- Find Python 3.10+ ---
find_python() {
    for cmd in python3 python python3.13 python3.12 python3.11 python3.10; do
        if command -v "$cmd" &>/dev/null; then
            local ver
            ver=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "0.0")
            local major minor
            major=$(echo "$ver" | cut -d. -f1)
            minor=$(echo "$ver" | cut -d. -f2)
            if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
                echo "$cmd"
                return 0
            fi
        fi
    done
    return 1
}

# --- Version comparison ---
version_gte() {
    local major minor
    major=$(echo "$1" | cut -d. -f1)
    minor=$(echo "$1" | cut -d. -f2)
    local req_major req_minor
    req_major=$(echo "$2" | cut -d. -f1)
    req_minor=$(echo "$2" | cut -d. -f2)
    [ "$major" -gt "$req_major" ] || { [ "$major" -eq "$req_major" ] && [ "$minor" -ge "$req_minor" ]; }
}

# --- Main ---
main() {
    printf "\n${BOLD}  Kiro Gateway Installer${RESET}\n"
    printf "${DIM}  Cross-platform proxy for Kiro API (Amazon Q Developer)${RESET}\n\n"

    # 1. Find Python
    info "Looking for Python >= $MIN_PYTHON..."
    PYTHON=$(find_python) || fail "Python 3.10+ not found. Install it first:
    Ubuntu/Debian: sudo apt install python3 python3-venv python3-pip
    Fedora:        sudo dnf install python3
    macOS:         brew install python@3.12
    Other:         https://www.python.org/downloads/"

    local pyver
    pyver=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')")
    ok "Found $PYTHON ($pyver)"

    # 2. Create install directory
    info "Setting up $INSTALL_DIR..."
    mkdir -p "$INSTALL_DIR" "$BIN_DIR"

    # 3. Create or reuse venv
    if [ -f "$VENV_DIR/bin/python" ]; then
        info "Virtual environment exists, reusing..."
    else
        info "Creating virtual environment..."
        "$PYTHON" -m venv "$VENV_DIR" || fail "Failed to create venv. Install python3-venv:
    Ubuntu/Debian: sudo apt install python3-venv"
    fi
    ok "Virtual environment ready"

    # 4. Install/upgrade kiro-gateway
    info "Installing kiro-gateway from GitHub (this may take a minute)..."
    "$VENV_DIR/bin/pip" install --upgrade --quiet "git+${REPO}" || fail "pip install failed. Check your internet connection."

    local installed_ver
    installed_ver=$("$VENV_DIR/bin/kiro-gateway" --version 2>/dev/null || echo "unknown")
    ok "Installed kiro-gateway $installed_ver"

    # 5. Create shell wrapper
    cat > "$BIN_DIR/kiro-gateway" << 'WRAPPER'
#!/usr/bin/env bash
# Kiro Gateway launcher - auto-generated by installer
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
exec "$SCRIPT_DIR/venv/bin/kiro-gateway" "$@"
WRAPPER
    chmod +x "$BIN_DIR/kiro-gateway"

    # 6. Create .env if not exists
    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << 'ENVFILE'
# Kiro Gateway Configuration
# Documentation: https://github.com/redok07/kiro-gateway#configuration

# Password to protect your proxy (CHANGE THIS!)
PROXY_API_KEY="CHANGE_ME_TO_A_STRONG_RANDOM_STRING"

# Authentication - uncomment ONE method:

# Option 1: Kiro IDE credentials file
# KIRO_CREDS_FILE="~/.aws/sso/cache/kiro-auth-token.json"

# Option 2: Refresh token (from Kiro IDE traffic)
# REFRESH_TOKEN="your_refresh_token_here"

# Option 3: kiro-cli SQLite database
# KIRO_CLI_DB_FILE="~/.local/share/kiro-cli/data.sqlite3"

# Server settings (defaults are fine for most users)
# SERVER_HOST="0.0.0.0"
# SERVER_PORT="8000"

# Debug logging: off | errors | all
# DEBUG_MODE="off"
ENVFILE
        ok "Created $ENV_FILE (edit this before starting!)"
    else
        info ".env already exists, keeping current config"
    fi

    # 7. Add to PATH
    add_to_path

    # 8. Done
    printf "\n${GREEN}${BOLD}  Installation complete!${RESET}\n\n"
    printf "  ${BOLD}Next steps:${RESET}\n"
    printf "  ${CYAN}1.${RESET} Edit your config:  ${DIM}nano $ENV_FILE${RESET}\n"
    printf "  ${CYAN}2.${RESET} Restart terminal (or run: source ~/.bashrc)\n"
    printf "  ${CYAN}3.${RESET} Start the gateway: ${DIM}kiro-gateway${RESET}\n"
    printf "\n"
    printf "  ${DIM}Or start immediately: $BIN_DIR/kiro-gateway${RESET}\n"
    printf "  ${DIM}Upgrade later:        curl -fsSL https://raw.githubusercontent.com/redok07/kiro-gateway/main/install.sh | bash${RESET}\n"
    printf "  ${DIM}Uninstall:            rm -rf $INSTALL_DIR${RESET}\n\n"
}

add_to_path() {
    # Check if already in PATH
    if echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
        info "$BIN_DIR already in PATH"
        return
    fi

    local shell_name profile export_line
    shell_name=$(basename "${SHELL:-/bin/bash}")

    case "$shell_name" in
        zsh)
            profile="$HOME/.zshrc"
            export_line="export PATH=\"$BIN_DIR:\$PATH\""
            ;;
        fish)
            profile="$HOME/.config/fish/config.fish"
            export_line="set -gx PATH \"$BIN_DIR\" \$PATH"
            ;;
        *)
            profile="$HOME/.bashrc"
            export_line="export PATH=\"$BIN_DIR:\$PATH\""
            ;;
    esac

    # Check if already added to profile
    if [ -f "$profile" ] && grep -qF "$BIN_DIR" "$profile"; then
        info "PATH entry already in $profile"
        return
    fi

    printf "\n# Kiro Gateway\n%s\n" "$export_line" >> "$profile"
    ok "Added to $profile"
}

main "$@"
